version: '3.8'

services:
  app:
    container_name: "glpi-app"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - glpi_files:/var/www/html/files
      - glpi_config:/var/www/html/config
      - glpi_marketplace:/var/www/html/marketplace
    ports:
      - "${PORT:-80}:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=${TIMEZONE:-UTC}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  db:
    container_name: "glpi-db"
    image: mariadb:11.8
    restart: unless-stopped
    volumes:
      - glpi_db:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-glpi_root}
      MARIADB_DATABASE: ${DB_DATABASE:-glpi}
      MARIADB_USER: ${DB_USER:-glpi}
      MARIADB_PASSWORD: ${DB_PASSWORD:-glpi}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-buffer-pool-size=512M
      - --max-allowed-packet=64M

volumes:
  glpi_db:
  glpi_files:
  glpi_config:
  glpi_marketplace:
