# Use this docker-compose file for deploying with an EXTERNAL database
# Usage: docker-compose -f docker-compose.external-db.yaml up -d

services:
  app:
    container_name: "glpi-app"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - glpi_files:/var/www/html/files
      - glpi_config:/var/www/html/config
      - glpi_marketplace:/var/www/html/marketplace
    expose:
      - "80"
    environment:
      - TZ=${TIMEZONE:-UTC}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-glpi}
      - DB_USER=${DB_USER:-glpi}
      - DB_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  glpi_files:
  glpi_config:
  glpi_marketplace:
